name: Java Frontend Build
on:
  push:
    branches:
      - main
      - github-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '16'

    - name: Install Dependencies
      run: mvn clean install --batch-mode --no-transfer-progress

    - name: Build
      run: mvn package --batch-mode --no-transfer-progress
      
    - name: Archive Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target
