name: Java Frontend Build
on:
  push:
    branches:
      - main
      - github-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Archive Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
